name: build ranchu kernel for KernelSU (x86_64)
on:
  workflow_dispatch:

jobs:
  build-ranchu-x86_64-kernel:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Check working directory
        run: |
            pwd && ls -la && echo ${{ github.workspace }}
            mkdir -p ${{ github.workspace }}/common-android15-6.6

      - name: Install dependencies
        run: |
            sudo apt update && sudo apt install -y git python3 curl rsync zip unzip cpio libncurses-dev libelf-dev bc flex bison build-essential libssl-dev

      - name: Configure git identity
        run: |
            git config --global user.name "github-actions[bot]"
            git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Install repo tool
        run: |
            sudo curl -sS https://storage.googleapis.com/git-repo-downloads/repo -o /usr/local/bin/repo
            sudo chmod a+x /usr/local/bin/repo

      - name: Sync kernel sources with repo
        working-directory: ${{ github.workspace }}/common-android15-6.6
        run: |
            repo init -u https://android.googlesource.com/kernel/manifest -b common-android15-6.6 --depth=1
            cp ${{ github.workspace }}/manifests/manifest_13070261.xml .repo/manifests/
            repo init -m manifest_13070261.xml
            repo sync -c --no-tags --no-clone-bundle -j$(nproc)

      - name: Calculate KSU version
        working-directory: ${{ github.workspace }}/common-android15-6.6
        run: |
            git clone --depth=1 https://github.com/tiann/KernelSU.git
            cd KernelSU
            KSU_VER=$(($(git rev-list --count HEAD) + 10200))
            echo "KSU_VER=$KSU_VER" >> $GITHUB_ENV

      - name: Patch kernelSU
        working-directory: ${{ github.workspace }}/common-android15-6.6/common
        run: |
            curl -LSs "https://raw.githubusercontent.com/tiann/KernelSU/main/kernel/setup.sh" | bash -s main
            sed -i '1i #define X86_FEATURE_INDIRECT_SAFE 1' drivers/kernelsu/core/init.c

            git add -A
            git commit -am "Add KernelSU"

            

      - name: Enable kernelSU value
        working-directory: ${{ github.workspace }}/common-android15-6.6
        run: |
            if [ -f common-modules/virtual-device/virtual_device_x86_64.fragment ]; then
                echo '文件存在! 写入到: common-modules/virtual-device/virtual_device_x86_64.fragment 下!'
                echo "CONFIG_KSU=y" >> common-modules/virtual-device/virtual_device_x86_64.fragment
            else
                echo '文件不存在! CONFIG_KSU 值写入到 common/arch/x86/configs/gki_defconfig'
                echo "CONFIG_KSU=y" >> common/arch/x86/configs/gki_defconfig
            fi
            


      - name: Total kernel usage
        working-directory: ${{ github.workspace }}/common-android15-6.6
        run: |
            echo "Total disk usage:"
            du -sh .

      - name: Build kernel
        working-directory: ${{ github.workspace }}/common-android15-6.6
        run: |
            tools/bazel run --config=fast --config=stamp --lto=none --action_env=KSU_VERSION=$KSU_VER //common-modules/virtual-device:virtual_device_x86_64_dist -- --dist_dir=virt
    
      - name: Upload Kernel Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ranchu-x86_64-kernel
          path: ${{ github.workspace }}/common-android15-6.6/virt/bzImage

